services:
  - type: web
    name: socialspace-backend
    env: node
    plan: free
    buildCommand: npm install && npm install nodemailer@6.9.7
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
